"""Type stubs for the _microsandbox native extension module."""

from __future__ import annotations

import os
from collections.abc import AsyncIterator
from typing import Any

from microsandbox.types import LogReadSource, LogSource

class PyAgentClient:
    @staticmethod
    async def connect_sandbox(
        name: str,
        *,
        timeout: float | None = None,
    ) -> PyAgentClient: ...
    @staticmethod
    async def connect(
        path: str,
        *,
        timeout: float | None = None,
    ) -> PyAgentClient: ...
    async def request(self, flags: int, body: bytes) -> dict[str, int | bytes]: ...
    async def stream_open(self, flags: int, body: bytes) -> dict[str, int]: ...
    async def stream_next(self, handle: int) -> dict[str, int | bytes] | None: ...
    async def stream_close(self, handle: int) -> None: ...
    async def send(self, id: int, flags: int, body: bytes) -> None: ...
    def ready_bytes(self) -> bytes: ...
    async def close(self) -> None: ...

class Sandbox:
    @staticmethod
    async def create(name_or_config: str | dict[str, Any], **kwargs: Any) -> Sandbox: ...
    @staticmethod
    async def start(name: str, *, detached: bool = False) -> Sandbox: ...
    @staticmethod
    async def get(name: str) -> SandboxHandle: ...
    @staticmethod
    async def list() -> list[SandboxHandle]: ...
    @staticmethod
    async def remove(name: str) -> None: ...
    @staticmethod
    def create_with_progress(
        name_or_config: str | dict[str, Any], **kwargs: Any
    ) -> PullSession: ...

    async def name(self) -> str: ...
    async def owns_lifecycle(self) -> bool: ...
    @property
    def fs(self) -> SandboxFs: ...

    async def exec(
        self, cmd: str, args_or_options: list[str] | dict[str, Any] | None = None
    ) -> ExecOutput: ...
    async def exec_stream(
        self, cmd: str, args_or_options: list[str] | dict[str, Any] | None = None
    ) -> ExecHandle: ...
    async def shell(self, script: str) -> ExecOutput: ...
    async def shell_stream(self, script: str) -> ExecHandle: ...
    async def attach(
        self, cmd: str, args_or_options: list[str] | dict[str, Any] | None = None
    ) -> int: ...
    async def attach_shell(self) -> int: ...
    async def metrics(self) -> SandboxMetrics: ...
    async def metrics_stream(self, interval: float = 1.0) -> MetricsStream: ...
    async def logs(
        self,
        tail: int | None = None,
        since_ms: float | None = None,
        until_ms: float | None = None,
        sources: list[LogReadSource] | None = None,
    ) -> list[LogEntry]: ...
    async def log_stream(
        self,
        sources: list[LogReadSource] | None = None,
        since_ms: float | None = None,
        from_cursor: str | None = None,
        until_ms: float | None = None,
        follow: bool = False,
    ) -> LogStream: ...
    async def stop(self) -> None: ...
    async def stop_and_wait(self) -> tuple[int, bool]: ...
    async def kill(self) -> None: ...
    async def drain(self) -> None: ...
    async def wait(self) -> tuple[int, bool]: ...
    async def detach(self) -> None: ...
    async def remove_persisted(self) -> None: ...
    async def __aenter__(self) -> Sandbox: ...
    async def __aexit__(
        self, exc_type: type | None, exc_val: BaseException | None, exc_tb: Any
    ) -> bool: ...

class SandboxHandle:
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def config_json(self) -> str: ...
    @property
    def created_at(self) -> float | None: ...
    @property
    def updated_at(self) -> float | None: ...
    async def metrics(self) -> SandboxMetrics: ...
    async def logs(
        self,
        tail: int | None = None,
        since_ms: float | None = None,
        until_ms: float | None = None,
        sources: list[LogReadSource] | None = None,
    ) -> list[LogEntry]: ...
    async def log_stream(
        self,
        sources: list[LogReadSource] | None = None,
        since_ms: float | None = None,
        from_cursor: str | None = None,
        until_ms: float | None = None,
        follow: bool = False,
    ) -> LogStream: ...
    async def start(self, *, detached: bool = False) -> Sandbox: ...
    async def connect(self) -> Sandbox: ...
    async def stop(self) -> None: ...
    async def kill(self) -> None: ...
    async def remove(self) -> None: ...
    async def snapshot(self, name: str) -> Snapshot: ...
    async def snapshot_to(self, path: str | os.PathLike[str]) -> Snapshot: ...

class ExecOutput:
    @property
    def exit_code(self) -> int: ...
    @property
    def success(self) -> bool: ...
    @property
    def stdout_text(self) -> str: ...
    @property
    def stderr_text(self) -> str: ...
    @property
    def stdout_bytes(self) -> bytes: ...
    @property
    def stderr_bytes(self) -> bytes: ...

class ExecHandle:
    @property
    async def id(self) -> str: ...
    @property
    def stdin(self) -> ExecSink | None: ...
    async def recv(self) -> ExecEvent | None: ...
    async def wait(self) -> tuple[int, bool]: ...
    async def collect(self) -> ExecOutput: ...
    async def signal(self, sig: int) -> None: ...
    async def kill(self) -> None: ...
    def __aiter__(self) -> AsyncIterator[ExecEvent]: ...
    async def __anext__(self) -> ExecEvent: ...

class ExecSink:
    async def write(self, data: bytes) -> None: ...
    async def close(self) -> None: ...

class ExecEvent:
    event_type: str
    pid: int | None
    data: bytes | None
    code: int | None

class SandboxFs:
    async def read(self, path: str) -> bytes: ...
    async def read_text(self, path: str) -> str: ...
    async def read_stream(self, path: str) -> FsReadStream: ...
    async def write(self, path: str, data: bytes) -> None: ...
    async def write_stream(self, path: str) -> FsWriteSink: ...
    async def list(self, path: str) -> list[FsEntry]: ...
    async def mkdir(self, path: str) -> None: ...
    async def remove(self, path: str) -> None: ...
    async def remove_dir(self, path: str) -> None: ...
    async def copy(self, src: str, dst: str) -> None: ...
    async def rename(self, src: str, dst: str) -> None: ...
    async def stat(self, path: str) -> FsMetadata: ...
    async def exists(self, path: str) -> bool: ...
    async def copy_from_host(self, host_path: str, guest_path: str) -> None: ...
    async def copy_to_host(self, guest_path: str, host_path: str) -> None: ...

class FsReadStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def __anext__(self) -> bytes: ...
    async def collect(self) -> bytes: ...

class FsWriteSink:
    async def write(self, data: bytes) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> FsWriteSink: ...
    async def __aexit__(
        self, exc_type: type | None, exc_val: BaseException | None, exc_tb: Any
    ) -> bool: ...

class FsEntry:
    path: str
    kind: str
    size: int
    mode: int
    modified: float | None

class FsMetadata:
    kind: str
    size: int
    mode: int
    readonly: bool
    modified: float | None
    created: float | None

class SandboxMetrics:
    cpu_percent: float
    memory_bytes: int
    memory_limit_bytes: int
    disk_read_bytes: int
    disk_write_bytes: int
    net_rx_bytes: int
    net_tx_bytes: int
    uptime_ms: int
    timestamp_ms: float

class MetricsStream:
    def __aiter__(self) -> AsyncIterator[SandboxMetrics]: ...
    async def __anext__(self) -> SandboxMetrics: ...

class LogEntry:
    timestamp_ms: float
    source: LogSource
    session_id: int | None  # None for `system` entries
    cursor: str  # opaque resume token, pass back via `from_cursor`
    @property
    def data(self) -> bytes: ...
    def text(self) -> str: ...

class LogStream:
    def __aiter__(self) -> AsyncIterator[LogEntry]: ...
    async def __anext__(self) -> LogEntry: ...

class Volume:
    @staticmethod
    async def create(
        name: str, *, quota_mib: int | None = None, labels: dict[str, str] | None = None
    ) -> Volume: ...
    @staticmethod
    async def get(name: str) -> VolumeHandle: ...
    @staticmethod
    async def list() -> list[VolumeHandle]: ...
    @staticmethod
    async def remove(name: str) -> None: ...
    @staticmethod
    def bind(path: str, *, readonly: bool = False) -> dict[str, Any]: ...
    @staticmethod
    def named(name: str, *, readonly: bool = False) -> dict[str, Any]: ...
    @staticmethod
    def tmpfs(*, size_mib: int | None = None, readonly: bool = False) -> dict[str, Any]: ...
    @staticmethod
    def disk(
        path: str,
        *,
        format: str | None = None,
        fstype: str | None = None,
        readonly: bool = False,
    ) -> dict[str, Any]: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...

class VolumeHandle:
    @property
    def name(self) -> str: ...
    @property
    def quota_mib(self) -> int | None: ...
    @property
    def used_bytes(self) -> int: ...
    @property
    def labels(self) -> dict[str, str]: ...
    @property
    def created_at(self) -> float | None: ...
    @property
    def fs(self) -> VolumeFs: ...
    async def remove(self) -> None: ...

class VolumeFs:
    async def read(self, path: str) -> bytes: ...
    async def read_text(self, path: str) -> str: ...
    async def write(self, path: str, data: bytes) -> None: ...
    async def list(self, path: str) -> list[FsEntry]: ...
    async def mkdir(self, path: str) -> None: ...
    async def remove_file(self, path: str) -> None: ...
    async def exists(self, path: str) -> bool: ...

class Snapshot:
    @staticmethod
    async def create(
        source_sandbox: str,
        *,
        name: str | None = None,
        path: str | os.PathLike[str] | None = None,
        labels: dict[str, str] | None = None,
        force: bool = False,
        record_integrity: bool = False,
    ) -> Snapshot: ...
    @staticmethod
    async def open(path_or_name: str) -> Snapshot: ...
    @staticmethod
    async def get(name_or_digest: str) -> SnapshotHandle: ...
    @staticmethod
    async def list() -> list[SnapshotHandle]: ...
    @staticmethod
    async def list_dir(dir: str | os.PathLike[str]) -> list[Snapshot]: ...
    @staticmethod
    async def remove(path_or_name: str, *, force: bool = False) -> None: ...
    @staticmethod
    async def reindex(dir: str | os.PathLike[str] | None = None) -> int: ...
    @staticmethod
    async def export(
        name_or_path: str,
        out: str | os.PathLike[str],
        *,
        with_parents: bool = False,
        with_image: bool = False,
        plain_tar: bool = False,
    ) -> None: ...
    @staticmethod
    async def import_(
        archive: str | os.PathLike[str],
        *,
        dest: str | os.PathLike[str] | None = None,
    ) -> SnapshotHandle: ...
    @property
    def path(self) -> str: ...
    @property
    def digest(self) -> str: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def image_ref(self) -> str: ...
    @property
    def image_manifest_digest(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def fstype(self) -> str: ...
    @property
    def parent(self) -> str | None: ...
    @property
    def created_at(self) -> str: ...
    @property
    def labels(self) -> dict[str, str]: ...
    @property
    def source_sandbox(self) -> str | None: ...
    async def verify(self) -> dict[str, Any]: ...

class SnapshotHandle:
    @property
    def digest(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def parent_digest(self) -> str | None: ...
    @property
    def image_ref(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def created_at(self) -> float: ...
    @property
    def path(self) -> str: ...
    async def open(self) -> Snapshot: ...
    async def remove(self, *, force: bool = False) -> None: ...

class PullSession:
    @property
    def progress(self) -> PullProgressIter: ...
    async def result(self) -> Sandbox: ...
    async def __aenter__(self) -> PullSession: ...
    async def __aexit__(
        self, exc_type: type | None, exc_val: BaseException | None, exc_tb: Any
    ) -> bool: ...

class PullProgressIter:
    def __aiter__(self) -> AsyncIterator[PullEvent]: ...
    async def __anext__(self) -> PullEvent: ...

class PullEvent:
    event_type: str
    reference: str | None
    manifest_digest: str | None
    layer_count: int | None
    total_download_bytes: int | None
    layer_index: int | None
    digest: str | None
    diff_id: str | None
    downloaded_bytes: int | None
    total_bytes: int | None
    bytes_read: int | None

async def all_sandbox_metrics() -> dict[str, SandboxMetrics]: ...
def install() -> None: ...
def is_installed() -> bool: ...
def resolved_msb_path() -> str: ...
def set_runtime_msb_path(path: str) -> None: ...
def version() -> str: ...
